version: '3.8'

services:
  postgres:
    image: postgres:14
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
        reservations:
          cpus: "1"
          memory: 2G

    environment:
      POSTGRES_DB: benchmark
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

    ports:
      - "5432:5432"

    command: >
      postgres
      -c shared_buffers=512MB
      -c effective_cache_size=1.5GB
      -c work_mem=16MB
      -c maintenance_work_mem=128MB
      -c max_parallel_workers=1
      -c max_parallel_workers_per_gather=0
      -c wal_buffers=16MB

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./generated:/generated

  neo4j:
    image: neo4j:5.26

    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
        reservations:
          cpus: "1"
          memory: 2G

    environment:
      NEO4J_AUTH: "neo4j/password"
      NEO4J_PLUGINS: '["apoc"]'

      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
      NEO4J_dbms_security_procedures_allowlist: "apoc.*"

      NEO4J_dbms_security_allow__csv__import__from__file__urls: "true"
      NEO4J_server_directories_import: "/var/lib/neo4j/import"

      NEO4J_server_memory_heap_initial__size: "512M"
      NEO4J_server_memory_heap_max__size: "768M"
      NEO4J_server_memory_pagecache_size: "1G"
      NEO4J_dbms_memory_transaction_total_max: "256M"

    ports:
      - "7474:7474"
      - "7687:7687"

    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./generated:/var/lib/neo4j/import/generated

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs: