version: '3.8'

services:
  postgres:
    image: postgres:14
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8G
        reservations:
          cpus: "4"
          memory: 8G

    environment:
      POSTGRES_DB: benchmark
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

    ports:
      - "5432:5432"

    command: >
      postgres
      -c shared_buffers=2GB
      -c effective_cache_size=5GB
      -c work_mem=64MB
      -c maintenance_work_mem=512MB
      -c max_parallel_workers=4
      -c max_parallel_workers_per_gather=2
      -c wal_buffers=64MB

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./generated:/generated

  neo4j:
    image: neo4j:5.26

    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8G
        reservations:
          cpus: "4"
          memory: 8G

    environment:
      NEO4J_AUTH: "neo4j/password"
      NEO4J_PLUGINS: '["apoc"]'

      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
      NEO4J_dbms_security_procedures_allowlist: "apoc.*"

      NEO4J_dbms_security_allow__csv__import__from__file__urls: "true"
      NEO4J_server_directories_import: "/var/lib/neo4j/import"

      NEO4J_server_memory_heap_initial__size: "2G"
      NEO4J_server_memory_heap_max__size: "3G"
      NEO4J_server_memory_pagecache_size: "4G"
      NEO4J_dbms_memory_transaction_total_max: "1G"

    ports:
      - "7474:7474"
      - "7687:7687"

    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./generated:/var/lib/neo4j/import/generated

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
