version: '3.8'

services:
  postgres:
    image: postgres:14
    
    deploy:
      resources:
        limits:
          cpus: '2.5'
          memory: 6144M
          pids: 1000
        reservations:
          cpus: '0.5'
          memory: 512M

    environment:
      POSTGRES_DB: benchmark
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

    ports:
      - "5432:5432"
    
    command: >
      postgres
      -c max_connections=100
      -c shared_buffers=1536MB
      -c work_mem=32MB
      -c maintenance_work_mem=384MB
      -c effective_cache_size=4608MB
      -c fsync=on
      -c synchronous_commit=on
      -c full_page_writes=on
      -c wal_buffers=16MB
      -c checkpoint_timeout=15min
      -c checkpoint_completion_target=0.9
      -c max_wal_size=4GB
      -c autovacuum=on
      -c autovacuum_max_workers=3
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c shared_preload_libraries='pg_stat_statements'
      -c log_min_duration_statement=1000
    
    networks:
      - benchmark_network
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./generated:/generated:ro

  neo4j:
    image: neo4j:5.26
    
    deploy:
      resources:
        limits:
          cpus: '2.5'
          memory: 6144M
          pids: 1000
        reservations:
          cpus: '0.5'
          memory: 512M
    
    environment:
      NEO4J_AUTH: "neo4j/password"
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
      NEO4J_dbms_security_allow__csv__import__from__file__urls: true
      NEO4J_server_directories_import: /import
      NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
      NEO4J_server_memory_heap_initial__size: 2G
      NEO4J_server_memory_heap_max__size: 2G
      NEO4J_server_memory_pagecache_size: 3500M
      NEO4J_dbms_memory_transaction_total_max: 512M
      NEO4J_db_transaction_concurrent_maximum: 50
      NEO4J_db_tx__log_rotation_size: 256M
      NEO4J_db_checkpoint_interval_time: 15m
      NEO4J_db_logs_query_threshold: 1000ms
      NEO4J_server_config_strict__validation_enabled: false
    
    networks:
      - benchmark_network
    
    ports:
      - "7474:7474"
      - "7687:7687"

    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - ./generated:/import/generated:ro
      - ./requirements/apoc.conf:/var/lib/neo4j/conf/apoc.conf

networks:
  benchmark_network:
    driver: bridge

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import: